//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5032HD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Article
    {
        public int ArticleID { get; set; }
        [Required(ErrorMessage = "Please enter a valid title")]
        [StringLength(50, ErrorMessage = "The maximum  length of title is 50")]
        [DisplayName("Title")]
        public string title { get; set; }

        [DisplayName("Date of publish")]
        public System.DateTime datePub { get; set; }

        [DisplayName("Description")]
        [StringLength(50, ErrorMessage = "The maximum length of description is 50")]
        public string description { get; set; }

        [DisplayName("Number of comments")]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid Number")]
        public string comments { get; set; }

        [Required(ErrorMessage = "Please enter a valid topic")]
        [StringLength(50, ErrorMessage = "The maximum length of topic is 50")]
        [DisplayName("Topic")]
        public string topic { get; set; }
        public string userID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
